[package]
name = "image_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.1"
tokio = { version = "1.37.0", features = [ "full" ]}
image = "0.25.1"
log = "0.4"
simplelog = "0.12"
rand = "0.8"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
